# Generated by Django 4.0.5 on 2022-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('review_date', models.DateField(auto_now=True, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
