# Generated by Django 4.0.5 on 2022-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_area_listing_borough_listing_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
        migrations.AddField(
            model_name='listing',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Inner London', 'Inner London'), ('Outer London', 'Outer London')], max_length=20, null=True),
        ),
    ]
