# Generated by Django 4.0.5 on 2022-06-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_location_listing_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='floor',
        ),
    ]
