# Generated by Django 4.0.5 on 2022-06-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listing_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_posted',
        ),
    ]
