# Generated by Django 4.0.5 on 2022-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_listing_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_posted',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
