# Generated by Django 4.0.5 on 2022-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
    ]
